// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package workflow

import (
	"context"
	"sync"
)

// Ensure, that WorkflowRepositoryMock does implement WorkflowRepository.
// If this is not the case, regenerate this file with moq.
var _ WorkflowRepository = &WorkflowRepositoryMock{}

// WorkflowRepositoryMock is a mock implementation of WorkflowRepository.
//
// 	func TestSomethingThatUsesWorkflowRepository(t *testing.T) {
//
// 		// make and configure a mocked WorkflowRepository
// 		mockedWorkflowRepository := &WorkflowRepositoryMock{
// 			GetFunc: func(ctx context.Context, id WorkflowID) (*Workflow, error) {
// 				panic("mock out the Get method")
// 			},
// 		}
//
// 		// use mockedWorkflowRepository in code that requires WorkflowRepository
// 		// and then make assertions.
//
// 	}
type WorkflowRepositoryMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id WorkflowID) (*Workflow, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID WorkflowID
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *WorkflowRepositoryMock) Get(ctx context.Context, id WorkflowID) (*Workflow, error) {
	if mock.GetFunc == nil {
		panic("WorkflowRepositoryMock.GetFunc: method is nil but WorkflowRepository.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  WorkflowID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedWorkflowRepository.GetCalls())
func (mock *WorkflowRepositoryMock) GetCalls() []struct {
	Ctx context.Context
	ID  WorkflowID
} {
	var calls []struct {
		Ctx context.Context
		ID  WorkflowID
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
