// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package employee

import (
	"context"
	"sync"
)

// Ensure, that EmployeeRepositoryMock does implement EmployeeRepository.
// If this is not the case, regenerate this file with moq.
var _ EmployeeRepository = &EmployeeRepositoryMock{}

// EmployeeRepositoryMock is a mock implementation of EmployeeRepository.
//
// 	func TestSomethingThatUsesEmployeeRepository(t *testing.T) {
//
// 		// make and configure a mocked EmployeeRepository
// 		mockedEmployeeRepository := &EmployeeRepositoryMock{
// 			GetFunc: func(ctx context.Context, id EmployeeID) (*Employee, error) {
// 				panic("mock out the Get method")
// 			},
// 		}
//
// 		// use mockedEmployeeRepository in code that requires EmployeeRepository
// 		// and then make assertions.
//
// 	}
type EmployeeRepositoryMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id EmployeeID) (*Employee, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID EmployeeID
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *EmployeeRepositoryMock) Get(ctx context.Context, id EmployeeID) (*Employee, error) {
	if mock.GetFunc == nil {
		panic("EmployeeRepositoryMock.GetFunc: method is nil but EmployeeRepository.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  EmployeeID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedEmployeeRepository.GetCalls())
func (mock *EmployeeRepositoryMock) GetCalls() []struct {
	Ctx context.Context
	ID  EmployeeID
} {
	var calls []struct {
		Ctx context.Context
		ID  EmployeeID
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
